# Generated by Django 5.2.4 on 2025-07-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blood',
            new_name='Donations',
        ),
    ]
