# Generated by Django 5.2.4 on 2025-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_main', '0002_rename_blood_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcenter',
            name='donation_date',
            field=models.DateField(default=2006),
        ),
    ]
