# Generated by Django 5.2.4 on 2025-07-11 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_main', '0002_rename_blood_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank_main.hospital'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank_main.person'),
        ),
    ]
