# Generated by Django 5.2.4 on 2025-07-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_main', '0003_donationcenter_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcenter',
            name='donation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
