# Generated by Django 5.2.4 on 2025-07-10 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_main', '0004_alter_donationcenter_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcenter',
            name='donation_date',
            field=models.DateField(default=datetime.date(2025, 7, 10)),
        ),
    ]
